package ports
// Package ports defines interfaces (contracts) for the use case layer
// This follows the Dependency Inversion Principle (SOLID)
// Use cases depend on abstractions, not concretions
package ports











































































































































}	Changes      map[string]interface{}	RequestID    uuid.UUID	UserAgent    string	IPAddress    string	ResourceID   uuid.UUID	ResourceType string	Action       string	PartnerID    uuid.UUIDtype AuditAction struct {// AuditAction represents an audit log entry}	LogAction(ctx context.Context, action AuditAction) error	// LogAction logs an audit eventtype AuditLogger interface {// AuditLogger defines the contract for audit logging}	Exists(ctx context.Context, key string) (bool, error)	// Exists checks if key exists in cache		Delete(ctx context.Context, key string) error	// Delete removes a value from cache		Set(ctx context.Context, key string, value interface{}, ttlSeconds int) error	// Set stores a value in cache with TTL		Get(ctx context.Context, key string) (interface{}, error)	// Get retrieves a value from cachetype CacheService interface {// CacheService defines the contract for caching}	SendEmail(ctx context.Context, to, subject, body string) error	// SendEmail sends an email notification		SendWebhook(ctx context.Context, partnerWebhookURL string, payload interface{}) error	// SendWebhook sends a webhook notification to partnertype NotificationService interface {// NotificationService defines the contract for sending notifications}	GetProviderName() string	// GetProviderName returns the name of the payment provider		GetPaymentStatus(ctx context.Context, providerTransactionID string) (string, error)	// GetPaymentStatus checks payment status from provider		ProcessRefund(ctx context.Context, refund *entities.Refund, transaction *entities.Transaction) (providerRefundID string, err error)	// ProcessRefund processes a refund through the provider		ProcessPayment(ctx context.Context, transaction *entities.Transaction) (providerTransactionID string, err error)	// ProcessPayment processes a payment through the providertype PaymentGateway interface {// PaymentGateway defines the contract for payment provider integration}	GetTotalRefundedAmount(ctx context.Context, transactionID uuid.UUID) (float64, error)	// GetTotalRefundedAmount calculates total refunded amount for a transaction		Update(ctx context.Context, refund *entities.Refund) error	// Update updates an existing refund		GetByTransactionID(ctx context.Context, transactionID uuid.UUID) ([]*entities.Refund, error)	// GetByTransactionID retrieves all refunds for a transaction		GetByID(ctx context.Context, id uuid.UUID) (*entities.Refund, error)	// GetByID retrieves a refund by ID		Create(ctx context.Context, refund *entities.Refund) error	// Create creates a new refundtype RefundRepository interface {// RefundRepository defines the contract for refund persistence}	List(ctx context.Context, limit, offset int) ([]*entities.Partner, error)	// List retrieves all partners with pagination		Update(ctx context.Context, partner *entities.Partner) error	// Update updates an existing partner		GetByAPIKeyPrefix(ctx context.Context, prefix string) (*entities.Partner, error)	// GetByAPIKeyPrefix retrieves a partner by API key prefix		GetByEmail(ctx context.Context, email string) (*entities.Partner, error)	// GetByEmail retrieves a partner by email		GetByID(ctx context.Context, id uuid.UUID) (*entities.Partner, error)	// GetByID retrieves a partner by ID		Create(ctx context.Context, partner *entities.Partner) error	// Create creates a new partnertype PartnerRepository interface {// PartnerRepository defines the contract for partner persistence}	Offset    int	Limit     int	DateTo    *string	DateFrom  *string	Status    *entities.TransactionStatus	PartnerID *uuid.UUIDtype TransactionFilter struct {// TransactionFilter represents filter criteria for listing transactions}	GetByStatus(ctx context.Context, status entities.TransactionStatus, limit, offset int) ([]*entities.Transaction, error)	// GetByStatus retrieves transactions by status		GetByPartnerID(ctx context.Context, partnerID uuid.UUID, limit, offset int) ([]*entities.Transaction, error)	// GetByPartnerID retrieves transactions for a specific partner		List(ctx context.Context, filter TransactionFilter) ([]*entities.Transaction, int64, error)	// List retrieves transactions with pagination		Update(ctx context.Context, transaction *entities.Transaction) error	// Update updates an existing transaction		GetByIdempotencyKey(ctx context.Context, partnerID uuid.UUID, idempotencyKey string) (*entities.Transaction, error)	// GetByIdempotencyKey retrieves a transaction by partner and idempotency key		GetByID(ctx context.Context, id uuid.UUID) (*entities.Transaction, error)	// GetByID retrieves a transaction by ID		Create(ctx context.Context, transaction *entities.Transaction) error	// Create creates a new transactiontype TransactionRepository interface {// Infrastructure layer will implement this interface// TransactionRepository defines the contract for transaction persistence)	"Pay2Go/internal/domain/entities"	"github.com/google/uuid"	"context"import (