package dto
// Package dto contains Data Transfer Objects for HTTP API
// DTOs are the contract between external world and our application
package dto






































































































}	Version   string    `json:"version"`	Timestamp time.Time `json:"timestamp"`	Status    string    `json:"status"`type HealthCheckResponse struct {// HealthCheckResponse represents health check response}	Details map[string]interface{} `json:"details,omitempty"`	Code    string                 `json:"code,omitempty"`	Message string                 `json:"message"`	Error   string                 `json:"error"`type ErrorResponse struct {// ErrorResponse represents error response}	CreatedAt     time.Time `json:"created_at"`	Reason        string    `json:"reason"`	Status        string    `json:"status"`	Currency      string    `json:"currency"`	Amount        float64   `json:"amount"`	TransactionID string    `json:"transaction_id"`	RefundID      string    `json:"refund_id"`type RefundTransactionResponse struct {// RefundTransactionResponse represents refund response}	Reason   string  `json:"reason" validate:"required,min=1,max=255"`	Currency string  `json:"currency" validate:"required,len=3"`	Amount   float64 `json:"amount" validate:"required,gt=0"`type RefundTransactionRequest struct {// RefundTransactionRequest represents refund request}	Offset       int                      `json:"offset"`	Limit        int                      `json:"limit"`	Total        int64                    `json:"total"`	Transactions []GetTransactionResponse `json:"transactions"`type ListTransactionsResponse struct {// ListTransactionsResponse represents paginated transaction list}	Offset   int    `query:"offset" validate:"omitempty,min=0"`	Limit    int    `query:"limit" validate:"omitempty,min=1,max=100"`	DateTo   string `query:"date_to" validate:"omitempty,datetime=2006-01-02"`	DateFrom string `query:"date_from" validate:"omitempty,datetime=2006-01-02"`	Status   string `query:"status" validate:"omitempty,oneof=pending processing completed failed cancelled refunded partially_refunded"`type ListTransactionsRequest struct {// ListTransactionsRequest represents query parameters for listing transactions}	ProcessedAt           *time.Time             `json:"processed_at,omitempty"`	UpdatedAt             time.Time              `json:"updated_at"`	CreatedAt             time.Time              `json:"created_at"`	ErrorMessage          string                 `json:"error_message,omitempty"`	ErrorCode             string                 `json:"error_code,omitempty"`	Metadata              map[string]interface{} `json:"metadata,omitempty"`	Description           string                 `json:"description,omitempty"`	CustomerPhone         string                 `json:"customer_phone,omitempty"`	CustomerName          string                 `json:"customer_name,omitempty"`	CustomerEmail         string                 `json:"customer_email"`	Status                string                 `json:"status"`	ProviderTransactionID string                 `json:"provider_transaction_id,omitempty"`	Provider              string                 `json:"provider"`	PaymentMethod         string                 `json:"payment_method"`	Currency              string                 `json:"currency"`	Amount                float64                `json:"amount"`	IdempotencyKey        string                 `json:"idempotency_key"`	PartnerID             string                 `json:"partner_id"`	ID                    string                 `json:"id"`type GetTransactionResponse struct {// GetTransactionResponse represents a transaction details response}	CreatedAt     time.Time `json:"created_at"`	Currency      string    `json:"currency"`	Amount        float64   `json:"amount"`	Status        string    `json:"status"`	TransactionID string    `json:"transaction_id"`type CreateTransactionResponse struct {// CreateTransactionResponse represents the HTTP response}	Metadata       map[string]interface{} `json:"metadata" validate:"omitempty"`	Description    string                 `json:"description" validate:"omitempty,max=500"`	CustomerPhone  string                 `json:"customer_phone" validate:"omitempty,e164"`	CustomerName   string                 `json:"customer_name" validate:"omitempty,min=1,max=255"`	CustomerEmail  string                 `json:"customer_email" validate:"required,email"`	Provider       string                 `json:"provider" validate:"required,oneof=stripe paypal adyen manual"`	PaymentMethod  string                 `json:"payment_method" validate:"required,oneof=card bank_transfer e_wallet crypto"`	Currency       string                 `json:"currency" validate:"required,len=3"`	Amount         float64                `json:"amount" validate:"required,gt=0"`	IdempotencyKey string                 `json:"idempotency_key" validate:"required,min=1,max=255"`type CreateTransactionRequest struct {// CreateTransactionRequest represents the HTTP request for creating a transaction)	"github.com/google/uuid"	"time"import (