package api
package main

import (
	"database/sql"












































































































































}	})		"error": err.Error(),	return c.Status(code).JSON(fiber.Map{	}		code = e.Code	if e, ok := err.(*fiber.Error); ok {	code := fiber.StatusInternalServerErrorfunc customErrorHandler(c *fiber.Ctx, err error) error {// customErrorHandler handles Fiber errors}	appLogger.Info("Server stopped")	}		appLogger.Error("Server shutdown failed: %v", err)	if err := app.Shutdown(); err != nil {	appLogger.Info("Shutting down server...")	<-quit	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)	quit := make(chan os.Signal, 1)	// Graceful shutdown	}()		}			os.Exit(1)			appLogger.Error("Server failed to start: %v", err)		if err := app.Listen(addr); err != nil {		appLogger.Info("Server starting on %s", addr)		addr := fmt.Sprintf("%s:%s", cfg.Server.Host, cfg.Server.Port)	go func() {	// Start server in goroutine	routes.SetupRoutes(app, transactionHandler, healthHandler, partnerRepo)	// Setup routes	})		ErrorHandler: customErrorHandler,		AppName:      "Pay2Go API",	app := fiber.New(fiber.Config{	// Initialize Fiber app	healthHandler := handlers.NewHealthHandler(db)	)		refundTransactionUC,		processPaymentUC,		listTransactionsUC,		getTransactionUC,		createTransactionUC,	transactionHandler := handlers.NewTransactionHandler(	// Initialize handlers	)		paymentGatewayFactory,		refundRepo,		partnerRepo,		transactionRepo,	refundTransactionUC := transaction.NewRefundTransactionUseCase(	)		paymentGatewayFactory,		partnerRepo,		transactionRepo,	processPaymentUC := transaction.NewProcessPaymentUseCase(	)		partnerRepo,		transactionRepo,	listTransactionsUC := transaction.NewListTransactionsUseCase(	)		partnerRepo,		transactionRepo,	getTransactionUC := transaction.NewGetTransactionUseCase(	)		paymentGatewayFactory,		partnerRepo,		transactionRepo,	createTransactionUC := transaction.NewCreateTransactionUseCase(	// Initialize use cases	}		return payment.NewPaymentGateway(provider)	paymentGatewayFactory := func(provider string) transaction.PaymentGateway {	// Initialize payment gateway factory	refundRepo := postgres.NewRefundRepository(db)	partnerRepo := postgres.NewPartnerRepository(db)	transactionRepo := postgres.NewTransactionRepository(db)	// Initialize repositories	appLogger.Info("Database connection established")	}		os.Exit(1)		appLogger.Error("Failed to ping database: %v", err)	if err := db.Ping(); err != nil {	// Test database connection	defer db.Close()	}		os.Exit(1)		appLogger.Error("Failed to connect to database: %v", err)	if err != nil {	db, err := sql.Open("postgres", cfg.Database.GetDSN())	// Connect to database	}		os.Exit(1)		appLogger.Error("Failed to load configuration: %v", err)	if err != nil {	cfg, err := config.Load()	// Load configuration	appLogger.Info("Starting Pay2Go API Server...")	appLogger := logger.New()	// Initialize loggerfunc main() {)	_ "github.com/lib/pq"	"github.com/gofiber/fiber/v2"	"Pay2Go/internal/usecases/transaction"	"Pay2Go/internal/infrastructure/payment"	"Pay2Go/internal/infrastructure/logger"	"Pay2Go/internal/infrastructure/config"	"Pay2Go/internal/adapters/persistence/postgres"	"Pay2Go/internal/adapters/http/routes"	"Pay2Go/internal/adapters/http/handlers"	"syscall"	"os/signal"	"os"	"log"	"fmt"