package config
// Package config manages application configuration
package config

import (
	"fmt"
	"os"
	"strconv"

























































































}	return value	}		return defaultValue	if err != nil {	value, err := strconv.Atoi(valueStr)	}		return defaultValue	if valueStr == "" {	valueStr := os.Getenv(key)func getEnvAsInt(key string, defaultValue int) int {// getEnvAsInt retrieves environment variable as integer or returns default}	return value	}		return defaultValue	if value == "" {	value := os.Getenv(key)func getEnv(key, defaultValue string) string {// getEnv retrieves environment variable or returns default}	)		c.Host, c.Port, c.User, c.Password, c.DBName, c.SSLMode,		"host=%s port=%s user=%s password=%s dbname=%s sslmode=%s",	return fmt.Sprintf(func (c *DatabaseConfig) GetDSN() string {// GetDSN returns PostgreSQL connection string}	return config, nil	}		return nil, fmt.Errorf("DB_PASSWORD is required")	if config.Database.Password == "" {	// Validate required fields	}		},			JWTSecret: getEnv("JWT_SECRET", "change-me-in-production"),		Security: SecurityConfig{		},			SSLMode:  getEnv("DB_SSLMODE", "disable"),			DBName:   getEnv("DB_NAME", "pay2go"),			Password: getEnv("DB_PASSWORD", ""),			User:     getEnv("DB_USER", "postgres"),			Port:     getEnv("DB_PORT", "5432"),			Host:     getEnv("DB_HOST", "localhost"),		Database: DatabaseConfig{		},			Host: getEnv("SERVER_HOST", "0.0.0.0"),			Port: getEnv("SERVER_PORT", "8080"),		Server: ServerConfig{	config := &Config{func Load() (*Config, error) {// Load loads configuration from environment variables}	JWTSecret stringtype SecurityConfig struct {// SecurityConfig holds security configuration}	SSLMode  string	DBName   string	Password string	User     string	Port     string	Host     stringtype DatabaseConfig struct {// DatabaseConfig holds database configuration}	Host string	Port stringtype ServerConfig struct {// ServerConfig holds server configuration}	Security SecurityConfig	Database DatabaseConfig	Server   ServerConfigtype Config struct {// Config holds all application configuration)